language: csharp
mono: none
dotnet: 2.2.101
dist: xenial
sudo: required
os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install avahi-daemon       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo lsof -i :5353                      ; fi
  - dotnet restore

script:
  - dotnet build -c Release --no-restore --framework netstandard2 ./src
  - dotnet test  -c Release --no-restore --framework netcoreapp2 ./test --filter TestCategory!=IPv6
  - dotnet test  -c Release --no-restore --framework netcoreapp2.1 ./test --filter TestCategory!=IPv6
  - dotnet test  -c Release --no-restore --framework netcoreapp2.2 ./test --filter TestCategory!=IPv6
