version: 2
general:
  branches:
    ignore:
      - gh-pages
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore --framework netstandard1.4 ./src
      - run: dotnet test  -c Release --no-restore --framework netcoreapp1.0 ./test
