version: 2
general:
  branches:
    ignore:
      - gh-pages
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:1.1-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build ./src -c Release --framework netstandard1.4 
      - run: dotnet test ./test -c Release --framework netcoreapp1.1
